version: 2.1

# Define the jobs we want to run for this project
jobs:
  prospector:
    docker:
      - image: sham51/nov-11-deploy
    steps:
      - checkout
      - restore_cache:
          key: python-dev-requirements
      - run: pip install -r requirements-dev.txt
      - save_cache:
          key: python-dev-requirements-3.9
          paths:
            - /usr/local/lib/python3.9/site-packages
#      - run: prospector apps

  tests:
    docker:
      - image: sham51/nov-11-deploy
    steps:
      - checkout
      - restore_cache:
          key: python-dev-requirements
      - run: pip install -r requirements-dev.txt
      - save_cache:
          key: python-dev-requirements-3.9
          paths:
            - /usr/local/lib/python3.9/site-packages
#      - run: coverage run ./manage.py test
#      - run: coverage report --fail-under=80

  deploy_dev:
    docker:
      - image: sham51/nov-11-deploy
    steps:
      - checkout
      - run: pip install boto3 pexpect
      - add_ssh_keys:
          fingerprints:
            - "c0:6b:91:ac:02:17:f5:e2:d2:a8:d9:cb:39:36:92:c0"
      - run: python deploy.py

# Orchestrate our job run sequence
workflows:
  check_code:
    jobs:
      - prospector
      - tests
      - deploy_dev:
          requires: ['prospector', 'tests']
          filters:
            branches:
              only:
                - main
